module.exports = function (results, treeData, title = '') {
    title = title ? ('The Index of \"' + title + '\"') : 'Index';
    let str = `<!DOCTYPE html>
        <html>
        <head>
        <title>${title}</title>
        <style type="text/css" media="screen">
        </style>
        </head>
        <body>
        <h1 id="header">${title}</h1>
        <div class="wrap">
        <ul class="index-list">
        `
    results.forEach(item => {
        str += `<li><h3><a href="${item}"   title="">${item}</a></h3></li>`
    })
    str += `
    </ul>
    <div class="footer">
    <p>Generated by <a href="https://github.com/icai/ndex">TestMM</a></p>
    </div>
    </div>
    </body>
    </html>`
    return str;
}