module.exports = function (results, treeData, title = '') {
    title = title ? ('The Index of \"' + title + '\"') : 'Index';
    let str = `<!DOCTYPE html>
        <html>
        <head>
        <title>${title}</title>
        <style type="text/css" media="screen">
        body {
            color: #333;
            font-size: 12px;
            font-family:"Microsoft YaHei",Arial,sans-serif;
            padding: 0;
            margin: 0
        }
        h1 {
            border-bottom: 1px solid #c0c0c0;
            margin-bottom: 10px;
            padding-bottom: 10px;
            white-space: nowrap;
            text-align: center;
        }
        a {
            color: #707070;
            text-decoration: none
        }
        a:hover {
            text-decoration: underline;
            color: #2d64b3
        }
        ul,li {
            list-style: none;
            padding: 0;
            margin: 0;
            white-space: pre;
        }
        .index-list::after {
            display: block;
            visibility: hidden;
            height: 0;
            clear: both;
            content: " "
        }
        .index-list li {
            padding-bottom: 10px;
            margin-bottom: 10px;
            border-bottom: 1px solid #e5e4e9;
        }

        h3 {
            color: #1a79ff;
            font-size: 18px;
            margin: 0;
        }

        .text-center{
        text-align:center;
        }
        .wrap {
        width: 1002px;
        margin: 100px auto 0;
        }

        .footer {
            display: block;
            float: left;
            width: 100%;
            padding-top: 30px
        }

        .footer p {
            text-align: center
        }
        </style>
        </head>
        <body>
        <h1 id="header">${title}</h1>
        <div class="wrap">
        <ul class="index-list">
        `
    results.forEach(item => {
        str += `<li><h3><a href="${item}"   title="">${item}</a></h3></li>`
    })
    str += `
    </ul>
    <div class="footer">
    <p>Generated by <a href="https://github.com/icai/ndex">ndex</a></p>
    </div>
    </div>
    </body>
    </html>`
    return str;
}